Reorg

diff --git a/scripts/mpv-for-vj b/scripts/mpv-for-vj
--- a/scripts/mpv-for-vj
+++ b/scripts/mpv-for-vj
@@ -1,15 +1,23 @@
 # Just an example; tweak to taste.
 # The most critical detail is that you give each MPV instance its own dedicated socket file.
-# The sample configs assumes a naming convention like `/tmp/mpv-socket.0`, `/tmp/mpv-socket.1`, etc.
-# Pass a dir or playlist argument to this script.
+# The sample mappers assume a naming convention like `/tmp/mpv-socket.0`, `/tmp/mpv-socket.1`, etc.
 
-# For Linux
+if [ "$1" = "" ]
+then
+  echo "Missing dir or playlist argument"
+  exit 1
+fi
+
+# The following works on my Mac and Linux systems. YMMV
 MPV=mpv
+MAC_MPV=/Applications/mpv.app/Contents/MacOS/mpv
+if [ -f $MAC_MPV ]
+then
+  MPV=$MAC_MPV
+fi
 
-# For MacOS
-MPV=/Applications/mpv.app/Contents/MacOS/mpv
-
-$MPV --input-ipc-server=/tmp/mpv-socket.0 --screen=0 --keep-open=yes --keep-open-pause=no --loop-playlist --fullscreen --loop-file=inf --video-osd=no "$*" &
+$MPV --input-ipc-server=/tmp/mpv-socket.0 --screen=0 --keep-open=yes --keep-open-pause=no --loop-playlist --fullscreen --loop-file=inf --video-osd=no "$1" &
 
 # Uncomment to run a second instance on the second screen
-#$MPV --input-ipc-server=/tmp/mpv-socket.1 --screen=1 --keep-open=yes --keep-open-pause=no --loop-playlist --fullscreen --loop-file=inf --video-osd=no "$*" &
+# In this example, we start with the same dir/playlist as the first.
+#$MPV --input-ipc-server=/tmp/mpv-socket.1 --screen=1 --keep-open=yes --keep-open-pause=no --loop-playlist --fullscreen --loop-file=inf --video-osd=no "$1" &
